### PR TITLE
[JIT] Added validation checks for stream literals

### PR DESCRIPTION
**Pull request by Kixiron**

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Comment by Kixiron** [comment]
@mihaibudiu The test case from #241 depends on uninit data, the step function looks like this, `v5` is never written to

```
fn(inout {?i64, ?i64} v1, input {i32} v2, input {i32} v3) {
  bb1:
    v4 = load {i32} v3[0] ; i32
    v5 = uninit {?i64, ?i64}
    jump bb2

  bb2:
    v6 = load {?i64, ?i64} v1[0] ; i64
    v7 = is_null {?i64, ?i64} v1[0]
    v8 = load {i32} v2[0] ; i32
    v9 = cast i32 v8 toi64
    v10 = bool false
    v11 = cast i32 v4 toi64
    v12 = mul i64 v9, v11
    v13 = or bool v10, v10
    br v7, bb3, bb4

  bb3:
    jump bb5(v12, v13)

  bb4:
    br v13, bb6, bb7

  bb5(i64 v16, bool v17):
    v18 = load {?i64, ?i64} v1[1] ; i64
    v19 = is_null {?i64, ?i64} v1[1]
    v20 = cast i32 v4 toi64
    br v19, bb8, bb9

  bb6:
    jump bb5(v6, v7)

  bb7:
    v14 = add i64 v6, v12
    v15 = bool false
    jump bb5(v14, v15)

  bb8:
    v21 = bool false
    jump bb10(v20, v21)

  bb9:
    v22 = add i64 v18, v20
    v23 = bool false
    jump bb10(v22, v23)

  bb10(i64 v24, bool v25):
    jump bb11

  bb11:
    v26 = load {?i64, ?i64} v5[0] ; i64
    v27 = is_null {?i64, ?i64} v5[0]
    store {?i64, ?i64} v1[0], i64 v26 ; v28
    set_null {?i64, ?i64} v1[0], v27 ; v29
    v30 = load {?i64, ?i64} v5[1] ; i64
    v31 = is_null {?i64, ?i64} v5[1]
    store {?i64, ?i64} v1[1], i64 v30 ; v32
    set_null {?i64, ?i64} v1[1], v31 ; v33
    ret unit
}
```

**Comment by mihaibudiu** [comment]
After some fixes that write the uninit value I still get the same panic. Test case:
```
#[test]
pub fn test0() {
    /* 
    6766 Source()
    7091 Map(6766)
        (t 1 input:[I32, F64, Bool, String, ?I32, ?F64], $retval_1 2 output:[I32])
        block 1()
            # (t.0)
            3 Load 1[0]
            # into Tuple1::new((t.0)).0
            4 Store 2[0]=3
            return #
    7112 IndexWith(7091)
        (t 1 input:[I32], $retval_1 2 output:[] (flattened), $retval_2 3 output:[I32] (flattened))
        block 1()
            # (t.0)
            4 Load 1[0]
            # into Tuple1::new((t.0)).0
            5 Store 3[0]=4
            return #
    7174 Fold(7112)
        init
            [(i64?)null, (i64?)null]
        step
            (a 1 inout:[?I64, ?I64], v 2 input:[I32], w 3 input:[I32])
            block 1()
                # (w.0)
                4 Load 3[0]
                # tmp0
                5 Uninit [?I64, ?I64]
                jump 2()
            block 2()
                # (a.0)
                6 Load 1[0]
                7 IsNull 1[0]
                # (v.0)
                8 Load 2[0]
                # ((i64?)(v.0))
                9 Cast 8 as I64
                10 Constant false
                # ((i64?)w)
                11 Cast 4 as I64
                # ((i64?)(v.0)) ?*? ((i64?)w)
                12 9 Mul 11
                13 10 Or 10
                if 7 then 3() else 4()
            block 3()
                jump 5(12, 13)
            block 4()
                if 13 then 6() else 7()
            block 5(16, 17)
                # into ((a.0) ?agg_plus? ((i64?)(v.0)) ?*? ((i64?)w), (a.1) ?agg_plus ((i64)w)).0
                18 Store 5[0]=16
                19 SetNull 5[0]=17
                # (a.1)
                20 Load 1[1]
                21 IsNull 1[1]
                # ((i64)w)
                22 Cast 4 as I64
                if 21 then 8() else 9()
            block 6()
                jump 5(6, 7)
            block 7()
                # (a.0) ?agg_plus? ((i64?)(v.0)) ?*? ((i64?)w)
                14 6 Add 12
                15 Constant false
                jump 5(14, 15)
            block 8()
                23 Constant false
                jump 10(22, 23)
            block 9()
                # (a.1) ?agg_plus ((i64)w)
                24 20 Add 22
                25 Constant false
                jump 10(24, 25)
            block 10(26, 27)
                # into ((a.0) ?agg_plus? ((i64?)(v.0)) ?*? ((i64?)w), (a.1) ?agg_plus ((i64)w)).1
                28 Store 5[1]=26
                29 SetNull 5[1]=27
                jump 11()
            block 11()
                # (tmp0.0)
                30 Load 5[0]
                31 IsNull 5[0]
                # into Tuple2::new((tmp0.0), (tmp0.1)).0
                32 Store 1[0]=30
                33 SetNull 1[0]=31
                # (tmp0.1)
                34 Load 5[1]
                35 IsNull 5[1]
                # into Tuple2::new((tmp0.0), (tmp0.1)).1
                36 Store 1[1]=34
                37 SetNull 1[1]=35
                return #
        finish
            (p0 1 input:[?I64, ?I64], $retval_1 2 output:[?I32])
            block 1()
                jump 2()
            block 2()
                # (p0.0)
                3 Load 1[0]
                4 IsNull 1[0]
                # (p0.1)
                5 Load 1[1]
                6 IsNull 1[1]
                7 Constant 0
                8 7 Eq 5
                if 8 then 3() else 4()
            block 3()
                9 Constant true
                jump 5(9, 7)
            block 4()
                10 4 Or 6
                # (p0.0) ?/? (p0.1)
                11 3 Div 5
                jump 5(10, 11)
            block 5(12, 13)
                # ((i32?)(p0.0) ?/? (p0.1))
                14 Cast 13 as I32
                jump 6()
            block 6()
                # into Tuple1::new(tmp0).0
                15 Store 2[0]=14
                16 SetNull 2[0]=12
                return #
    7196 Map(7174)
        (p_0 1 input:[], p_1 2 input:[?I32], $retval_2 3 output:[?I32])
        block 1()
            # (p_1.0)
            4 Load 2[0]
            5 IsNull 2[0]
            # into Tuple1::new((p_1.0)).0
            6 Store 3[0]=4
            7 SetNull 3[0]=5
            return #
    7211 Map(7196)
        (_t 1 input:[?I32], $retval_1 2 output:[?I32])
        block 1()
            3 Constant (i32?)null
            4 Constant true
            # into Tuple1::new((i32?)null).0
            5 Store 2[0]=3
            6 SetNull 2[0]=4
            return #
    7215 Neg(7211)
    7223 Constant()
        {[(i32?)null]}
    7226 Sum(7223, 7215, 7196)
    7229 Sink(7226)
     */
    const CIRCUIT: &str = r#"{
      "nodes" : {
        "6766" : {
          "Source" : {
            "layout" : 1,
            "table" : "T"
          }
        },
        "7091" : {
          "Map" : {
            "input" : 6766,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 1,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 2,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 3, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 1,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 4, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 2,
                      "column" : 0,
                      "value" : {
                        "Expr" : 3
                      },
                      "value_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "input_layout" : {
              "Set" : 1
            },
            "output_layout" : {
              "Set" : 2
            }
          }
        },
        "7112" : {
          "IndexWith" : {
            "input" : 7091,
            "index_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 2,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 3,
                "flags" : "output"
              }, {
                "id" : 3,
                "layout" : 2,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 2,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 2,
                      "column" : 0,
                      "value" : {
                        "Expr" : 4
                      },
                      "value_type" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "key_layout" : 3,
            "value_layout" : 2
          }
        },
        "7174" : {
          "Fold" : {
            "input" : 7112,
            "acc_layout" : 5,
            "step_layout" : 2,
            "output_layout" : 4,
            "finish_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 5,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 4,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 2,
                      "params" : [ ]
                    }
                  },
                  "params" : [ ]
                },
                "2" : {
                  "id" : 2,
                  "body" : [ [ 3, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 0,
                      "column_type" : "I64"
                    }
                  } ], [ 4, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0
                    }
                  } ], [ 5, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 1,
                      "column_type" : "I64"
                    }
                  } ], [ 6, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1
                    }
                  } ], [ 7, {
                    "Constant" : {
                      "I64" : 0
                    }
                  } ], [ 8, {
                    "BinOp" : {
                      "lhs" : 7,
                      "rhs" : 5,
                      "kind" : "Eq",
                      "operand_ty" : "I64"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 8
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 4,
                      "truthy" : 3
                    }
                  },
                  "params" : [ ]
                },
                "3" : {
                  "id" : 3,
                  "body" : [ [ 9, {
                    "Constant" : {
                      "Bool" : true
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 9, 7 ]
                    }
                  },
                  "params" : [ ]
                },
                "4" : {
                  "id" : 4,
                  "body" : [ [ 10, {
                    "BinOp" : {
                      "lhs" : 4,
                      "rhs" : 6,
                      "kind" : "Or",
                      "operand_ty" : "Bool"
                    }
                  } ], [ 11, {
                    "BinOp" : {
                      "lhs" : 3,
                      "rhs" : 5,
                      "kind" : "Div",
                      "operand_ty" : "I64"
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 10, 11 ]
                    }
                  },
                  "params" : [ ]
                },
                "5" : {
                  "id" : 5,
                  "body" : [ [ 14, {
                    "Cast" : {
                      "value" : 13,
                      "from" : "I64",
                      "to" : "I32"
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 6,
                      "params" : [ ]
                    }
                  },
                  "params" : [ [ 12, {
                    "Scalar" : "Bool"
                  } ], [ 13, {
                    "Scalar" : "I64"
                  } ] ]
                },
                "6" : {
                  "id" : 6,
                  "body" : [ [ 15, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 4,
                      "column" : 0,
                      "value" : {
                        "Expr" : 14
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 16, {
                    "SetNull" : {
                      "target" : 2,
                      "target_layout" : 4,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 12
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "step_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 5,
                "flags" : "inout"
              }, {
                "id" : 2,
                "layout" : 2,
                "flags" : "input"
              }, {
                "id" : 3,
                "layout" : 2,
                "flags" : "input"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 3,
                      "source_layout" : 2,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "Uninit" : {
                      "value" : {
                        "Row" : 6
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 2,
                      "params" : [ ]
                    }
                  },
                  "params" : [ ]
                },
                "2" : {
                  "id" : 2,
                  "body" : [ [ 6, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 0,
                      "column_type" : "I64"
                    }
                  } ], [ 7, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0
                    }
                  } ], [ 8, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 2,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 9, {
                    "Cast" : {
                      "value" : 8,
                      "from" : "I32",
                      "to" : "I64"
                    }
                  } ], [ 10, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ], [ 11, {
                    "Cast" : {
                      "value" : 4,
                      "from" : "I32",
                      "to" : "I64"
                    }
                  } ], [ 12, {
                    "BinOp" : {
                      "lhs" : 9,
                      "rhs" : 11,
                      "kind" : "Mul",
                      "operand_ty" : "I64"
                    }
                  } ], [ 13, {
                    "BinOp" : {
                      "lhs" : 10,
                      "rhs" : 10,
                      "kind" : "Or",
                      "operand_ty" : "Bool"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 7
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 4,
                      "truthy" : 3
                    }
                  },
                  "params" : [ ]
                },
                "3" : {
                  "id" : 3,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 12, 13 ]
                    }
                  },
                  "params" : [ ]
                },
                "4" : {
                  "id" : 4,
                  "body" : [ ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 13
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 7,
                      "truthy" : 6
                    }
                  },
                  "params" : [ ]
                },
                "5" : {
                  "id" : 5,
                  "body" : [ [ 18, {
                    "Store" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 0,
                      "value" : {
                        "Expr" : 16
                      },
                      "value_type" : "I64"
                    }
                  } ], [ 19, {
                    "SetNull" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 17
                      }
                    }
                  } ], [ 20, {
                    "Load" : {
                      "source" : 1,
                      "source_layout" : 5,
                      "column" : 1,
                      "column_type" : "I64"
                    }
                  } ], [ 21, {
                    "IsNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1
                    }
                  } ], [ 22, {
                    "Cast" : {
                      "value" : 4,
                      "from" : "I32",
                      "to" : "I64"
                    }
                  } ] ],
                  "terminator" : {
                    "Branch" : {
                      "cond" : {
                        "Expr" : 21
                      },
                      "true_params" : [ ],
                      "false_params" : [ ],
                      "falsy" : 9,
                      "truthy" : 8
                    }
                  },
                  "params" : [ [ 16, {
                    "Scalar" : "I64"
                  } ], [ 17, {
                    "Scalar" : "Bool"
                  } ] ]
                },
                "6" : {
                  "id" : 6,
                  "body" : [ ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 6, 7 ]
                    }
                  },
                  "params" : [ ]
                },
                "7" : {
                  "id" : 7,
                  "body" : [ [ 14, {
                    "BinOp" : {
                      "lhs" : 6,
                      "rhs" : 12,
                      "kind" : "Add",
                      "operand_ty" : "I64"
                    }
                  } ], [ 15, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 5,
                      "params" : [ 14, 15 ]
                    }
                  },
                  "params" : [ ]
                },
                "8" : {
                  "id" : 8,
                  "body" : [ [ 23, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 10,
                      "params" : [ 22, 23 ]
                    }
                  },
                  "params" : [ ]
                },
                "9" : {
                  "id" : 9,
                  "body" : [ [ 24, {
                    "BinOp" : {
                      "lhs" : 20,
                      "rhs" : 22,
                      "kind" : "Add",
                      "operand_ty" : "I64"
                    }
                  } ], [ 25, {
                    "Constant" : {
                      "Bool" : false
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 10,
                      "params" : [ 24, 25 ]
                    }
                  },
                  "params" : [ ]
                },
                "10" : {
                  "id" : 10,
                  "body" : [ [ 28, {
                    "Store" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 1,
                      "value" : {
                        "Expr" : 26
                      },
                      "value_type" : "I64"
                    }
                  } ], [ 29, {
                    "SetNull" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 1,
                      "is_null" : {
                        "Expr" : 27
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Jump" : {
                      "target" : 11,
                      "params" : [ ]
                    }
                  },
                  "params" : [ [ 26, {
                    "Scalar" : "I64"
                  } ], [ 27, {
                    "Scalar" : "Bool"
                  } ] ]
                },
                "11" : {
                  "id" : 11,
                  "body" : [ [ 30, {
                    "Load" : {
                      "source" : 5,
                      "source_layout" : 6,
                      "column" : 0,
                      "column_type" : "I64"
                    }
                  } ], [ 31, {
                    "IsNull" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 0
                    }
                  } ], [ 32, {
                    "Store" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0,
                      "value" : {
                        "Expr" : 30
                      },
                      "value_type" : "I64"
                    }
                  } ], [ 33, {
                    "SetNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 31
                      }
                    }
                  } ], [ 34, {
                    "Load" : {
                      "source" : 5,
                      "source_layout" : 6,
                      "column" : 1,
                      "column_type" : "I64"
                    }
                  } ], [ 35, {
                    "IsNull" : {
                      "target" : 5,
                      "target_layout" : 6,
                      "column" : 1
                    }
                  } ], [ 36, {
                    "Store" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1,
                      "value" : {
                        "Expr" : 34
                      },
                      "value_type" : "I64"
                    }
                  } ], [ 37, {
                    "SetNull" : {
                      "target" : 1,
                      "target_layout" : 5,
                      "column" : 1,
                      "is_null" : {
                        "Expr" : 35
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "init" : {
              "rows" : [ {
                "Nullable" : null
              }, {
                "Nullable" : null
              } ]
            }
          }
        },
        "7196" : {
          "Map" : {
            "input" : 7174,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 3,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 4,
                "flags" : "input"
              }, {
                "id" : 3,
                "layout" : 4,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 4, {
                    "Load" : {
                      "source" : 2,
                      "source_layout" : 4,
                      "column" : 0,
                      "column_type" : "I32"
                    }
                  } ], [ 5, {
                    "IsNull" : {
                      "target" : 2,
                      "target_layout" : 4,
                      "column" : 0
                    }
                  } ], [ 6, {
                    "Store" : {
                      "target" : 3,
                      "target_layout" : 4,
                      "column" : 0,
                      "value" : {
                        "Expr" : 4
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 7, {
                    "SetNull" : {
                      "target" : 3,
                      "target_layout" : 4,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 5
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "input_layout" : {
              "Map" : [ 3, 4 ]
            },
            "output_layout" : {
              "Set" : 4
            }
          }
        },
        "7211" : {
          "Map" : {
            "input" : 7196,
            "map_fn" : {
              "args" : [ {
                "id" : 1,
                "layout" : 4,
                "flags" : "input"
              }, {
                "id" : 2,
                "layout" : 4,
                "flags" : "output"
              } ],
              "ret" : "Unit",
              "entry_block" : 1,
              "blocks" : {
                "1" : {
                  "id" : 1,
                  "body" : [ [ 3, {
                    "Constant" : {
                      "I32" : 0
                    }
                  } ], [ 4, {
                    "Constant" : {
                      "Bool" : true
                    }
                  } ], [ 5, {
                    "Store" : {
                      "target" : 2,
                      "target_layout" : 4,
                      "column" : 0,
                      "value" : {
                        "Expr" : 3
                      },
                      "value_type" : "I32"
                    }
                  } ], [ 6, {
                    "SetNull" : {
                      "target" : 2,
                      "target_layout" : 4,
                      "column" : 0,
                      "is_null" : {
                        "Expr" : 4
                      }
                    }
                  } ] ],
                  "terminator" : {
                    "Return" : {
                      "value" : {
                        "Imm" : "Unit"
                      }
                    }
                  },
                  "params" : [ ]
                }
              }
            },
            "input_layout" : {
              "Set" : 4
            },
            "output_layout" : {
              "Set" : 4
            }
          }
        },
        "7215" : {
          "Neg" : {
            "input" : 7211,
            "layout" : {
              "Set" : 4
            }
          }
        },
        "7223" : {
          "ConstantStream" : {
            "comment" : "zset!(Tuple1::new((i32?)null) => 1,)",
            "layout" : {
              "Set" : 4
            },
            "value" : {
              "layout" : {
                "Set" : 4
              },
              "value" : {
                "Set" : [ [ {
                  "rows" : [ {
                    "Nullable" : null
                  } ]
                }, 1 ] ]
              }
            },
            "consolidated" : false
          }
        },
        "7226" : {
          "Sum" : {
            "layout" : {
              "Set" : 4
            },
            "inputs" : [ 7223, 7215, 7196 ]
          }
        },
        "7229" : {
          "Sink" : {
            "input" : 7226,
            "comment" : "CREATE VIEW V AS SELECT AVG(T.COL1) FROM T",
            "input_layout" : {
              "Set" : 4
            }
          }
        }
      },
      "layouts" : {
        "3" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "Unit"
          } ]
        },
        "1" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          }, {
            "nullable" : false,
            "ty" : "F64"
          }, {
            "nullable" : false,
            "ty" : "Bool"
          }, {
            "nullable" : false,
            "ty" : "String"
          }, {
            "nullable" : true,
            "ty" : "I32"
          }, {
            "nullable" : true,
            "ty" : "F64"
          } ]
        },
        "5" : {
          "columns" : [ {
            "nullable" : true,
            "ty" : "I64"
          }, {
            "nullable" : true,
            "ty" : "I64"
          } ]
        },
        "6" : {
          "columns" : [ {
            "nullable" : true,
            "ty" : "I64"
          }, {
            "nullable" : true,
            "ty" : "I64"
          } ]
        },
        "2" : {
          "columns" : [ {
            "nullable" : false,
            "ty" : "I32"
          } ]
        },
        "4" : {
          "columns" : [ {
            "nullable" : true,
            "ty" : "I32"
          } ]
        }
      }
    }"#;
    let graph = serde_json::from_str::<SqlGraph>(CIRCUIT).unwrap().rematerialize();
    let graph_nodes = graph.nodes();
    let mut demands = Demands::new();
    let T_id = NodeId::new(6766u32);
    let T_layout = (graph_nodes[&T_id]).clone().unwrap_source().layout();
    let mut circuit = DbspCircuit::new(graph, true, 1usize, CodegenConfig::debug(), demands);
    circuit.append_input(T_id, &Set(vec!(
        (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(1.0)), NonNull(Constant::Bool(false)), NonNull(Constant::String(String::from("Hi"))), Nullable(Some(Constant::I32(1i32))), Nullable(Some(Constant::F64(0.0))), )), 1i32, ), (RowLiteral::new(vec!(
            NonNull(Constant::I32(10i32)), NonNull(Constant::F64(12.0)), NonNull(Constant::Bool(true)), NonNull(Constant::String(String::from("Hi"))), NullableConstant::null(), NullableConstant::null(), )), 1i32, ), )));
    circuit.step().unwrap();
    let V = circuit.consolidate_output(NodeId::new(7229u32));
    assert!(must_equal_sc(&V, &Set(vec!(
        (RowLiteral::new(vec!(
            Nullable(Some(Constant::I32(10i32))), )), 1i32, ), ))));
    circuit.kill().unwrap();
}
```

**Comment by mihaibudiu** [comment]
BTW: I suspect that the Uninit needs a Drop, is that right?

**Comment by Kixiron** [comment]
I'm not really sure what the issue with CI is, it looks like it happens in Java code?

**Comment by Kixiron** [comment]
>BTW: I suspect that the Uninit needs a Drop, is that right?

Sometimes, yes. It's just data so if it's left initialized (that is, if you don't move all of the values it contains to outputs or something) then it does need to be dropped or it'll leak memory. However, if you use `CopyRowTo` or manually move columns/fields then dropping it will invalidate those moved columns and is UB.

**Comment by mihaibudiu** [comment]
Yes, your changes broke some of the JitTests.
Unfortunately the logs don't say what broke.
You can try to run the failing test with:
```
cd sql-to-dbsp-compiler/SQL-compiler
mvn test -Dtest=JitTests
```

**Comment by Kixiron** [comment]
Got it down to this @mihaibudiu
```
[DEBUG] failures:
[DEBUG] ---- test14 stdout ----
[DEBUG] R: RowLiteral { rows: [NonNull(I32(10)), NonNull(I64(1))] }x1
[DEBUG] thread 'test14' panicked at 'assertion failed: must_equal_sc(&V,\n    &Set(vec!((RowLiteral ::\n                new(vec!\n                (NonNull(Constant :: I32(10i32)),\n                NonNull(Constant :: I64(1i64)),)), 2i32,),)))', src/lib.rs:5464:5
[DEBUG] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[DEBUG] failures:
[DEBUG]     test14
[DEBUG] test result: FAILED. 60 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.02s
```

**Comment by mihaibudiu** [comment]
Looks like a query is producing an incorrect result.
This is in test14.
This most likely used to work - but perhaps it was by chance.

**Comment by mihaibudiu** [comment]
The expected result has an extra row, which is missing from the produced result.

**Comment by mihaibudiu** [comment]
test14 is a rust test in sql-to-dbsp-compiler/temp/src

**Pull request merged**
