### PR TITLE
Get persistence feature compiling again

### PR DESCRIPTION
**Pull request by blp**
Plus tiny improvements.

### CODE REVIEW

**Review by ryzhyk — APPROVED** [review]

**Review by gz — APPROVED** [review]
lgtm, I'm going to add a commit that makes this build & tested again in CI. then we can merge

**Comment by ryzhyk** [comment]
@gz , let's make sure we don't slow down the CI too much.  I think some of the tests added recently are slow with persistence.  Maybe just a small subset is good enough?

**Comment by gz** [comment]
@blp I updated the build, can be merged from my side

**Comment by blp** [comment]
> @blp I updated the build, can be merged from my side

Thanks, I did that.

> @gz , let's make sure we don't slow down the CI too much. I think some of the tests added recently are slow with persistence. Maybe just a small subset is good enough?

I'm going to guess that what @gz did was good enough for that, but obviously I support making the CI faster.

**Pull request merged**
