### PR TITLE
Merge SQL compiler into source tree.

### PR DESCRIPTION
**Pull request by blp**
This merges the contents of commit 9cd82b1400ed ("Merge pull request #27 from mihaibudiu/jitrun") into the dbsp tree, replacing the submodule.

### CODE REVIEW

**Comment by blp** [comment]
I did a force-push to:
1. Fold in @mihaibudiu's new changes to the upstream repo.
2. Squash the fixes based on his suggestions that I pushed earlier.

**Review by mihaibudiu — APPROVED** [review]

**Comment by blp** [comment]
@gz I'm getting a build failure in the CI above, that I don't see locally from Earthly. It makes me reluctant to merge. When you have time, do you have any thoughts?

**Comment by gz** [comment]
@blp I tried the branch -- strange but I'm getting the same error as CI in earthly locally, also just running `mvn -DskipTests package` in `sql-to-dbsp-compiler/SQL-compiler` doesn't build for me.

**Comment by lalithsuresh** [comment]
@mihaibudiu I thought you removed zetatest?

**Comment by mihaibudiu** [comment]
Long time ago

**Comment by blp** [comment]
> @blp I tried the branch -- strange but I'm getting the same error as CI in earthly locally, also just running `mvn -DskipTests package` in `sql-to-dbsp-compiler/SQL-compiler` doesn't build for me.

Thanks for checking. I'll dig deeper.

**Comment by lalithsuresh** [comment]
Building from this branch gives me the same error, but I'm able to build feldera/sql2dbsp's main branch just fine.

**Comment by blp** [comment]
This time for sure. I think the problem was just that I hadn't added a few stray files.

**Comment by blp** [comment]
Eh, false optimism I guess.

**Comment by blp** [comment]
Oh, c'mon, it's not fair to fail the build because some new vulnerability report has been filed.

**Comment by gz** [comment]
We may want to run the audit every night, or put it in front of the docker release build so we just block the release when there is a security issues instead of a merge with main (where the problem usually exists too so blocking the merge is not very helpful anyways). @ryzhyk wdyt?

I'm also not sure if audit is redundant with https://github.com/feldera/dbsp/security/dependabot or if they check separate things?

**Comment by blp** [comment]
> We may want to run the audit every night, or put it in front of the docker release build so we just block the release when there are security issues instead of a merge with main (where the problem usually exists too so blocking the merge is not very helpful anyways).

For now, I added `-D yanked` to the `cargo audit` so that the worst breakages stop the build, but not the others.

It's just a stopgap.

**Comment by blp** [comment]
> For now, I added `-D yanked` to the `cargo audit` so that the worst breakages stop the build, but not the others.

Argh, it didn't work.

**Comment by gz** [comment]
Putting no-default-features = true in the Cargo file for the pg-embed dependency in the pipeline manager might help to throw out these dependencies (they should not be used by anything). It might get pulled in anyways because we use tokio in our crate but it's worth a try.

**Comment by blp** [comment]
> Putting no-default-features = true in the Cargo file for the pg-embed dependency in the pipeline manager might help to throw out these dependencies (they should not be used by anything). It might get pulled in anyways because we use tokio in our crate but it's worth a try.

They're also used by `sqllib` and `readers` in the generated SQL compiler helper library, and probably for good reason.

**Comment by ryzhyk** [comment]
> We may want to run the audit every night, or put it in front of the docker release build so we just block the release when there are security issues instead of a merge with main (where the problem usually exists too so blocking the merge is not very helpful anyways). @ryzhyk wdyt?

I'm ok with this, although if the vulnerability is introduced by the new commit, you may want to see it straight away.

**Comment by blp** [comment]
> > We may want to run the audit every night, or put it in front of the docker release build so we just block the release when there are security issues instead of a merge with main (where the problem usually exists too so blocking the merge is not very helpful anyways). @ryzhyk wdyt?
> 
> I'm ok with this, although if the vulnerability is introduced by the new commit, you may want to see it straight away.

I guess the case where you want an immediate failure is "this commit has a vuln that a simultaneous build of of the tip of `main` would not have".

**Pull request merged**
