### PR TITLE
Introduce aggregate_simple_linear function

### PR DESCRIPTION
**Pull request by mihaibudiu**
Aggregation functions almost never care about the key. So I added a aggregate_simple_linear method which takes a function that ignores the key and just calls aggregate_linear. 

In fact, I am wondering whether the aggregation function can ever depend on the key while still being linear.

### CODE REVIEW

**Review by ryzhyk — APPROVED** [review]
Looks good.  Not a very descriptive name, but I can't think of a better option. @blp , any suggestions?

**Comment by blp** [comment]
When I did some work in this area before, I was puzzled why `Aggregate` receives just values but `aggregate_linear` gets both the key and the value. I think it would be better to be consistent, that is, to make `aggregate_linear` only pass the value. That would be a better change, in my opinion, than adding a new API. If some particular aggregation needs the key, you can always do a prior `map_index(|(k, v)| (k, (k, v))|` or similar.

**Comment by mihaibudiu** [comment]
The plan is then to submit a new PR which uses the new implementation for the old functions.
I will do this after I merge the compiler support for linear aggregations, which uses the current API.

**Comment by mihaibudiu** [comment]
I have updated the commit to simplify several linear aggregation operations to ignore the keys.

**Review by blp — APPROVED** [review]
> I have updated the commit to simplify several linear aggregation operations to ignore the keys.

Perfect, thank you!

**Review by ryzhyk — APPROVED** [review]

**Pull request merged**
